from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os
from typing import Dict, List, Optional
import pandas as pd


def generate_model_card_pdf(
    output_path: str,
    dataset_name: str,
    dataset_info: Dict,
    ml_config: Dict,
    metrics: Dict,
    chart_paths: List[str] = None,
    feature_importance: List[tuple] = None
) -> bool:
    """
    Generate a professional PDF Model Card report.
    
    Args:
        output_path: Where to save the PDF
        dataset_name: Name of the dataset
        dataset_info: Dict with dataset statistics (rows, columns, missing_values, etc.)
        ml_config: Dict with ML configuration (task_type, target_column, model_type)
        metrics: Dict with model performance metrics
        chart_paths: List of paths to chart images
        feature_importance: List of (feature_name, importance_value) tuples
    
    Returns:
        True if successful, False otherwise
    """
    try:
        # Create PDF document
        doc = SimpleDocTemplate(output_path, pagesize=letter,
                                rightMargin=72, leftMargin=72,
                                topMargin=72, bottomMargin=18)
        
        # Container for the 'Flowable' objects
        elements = []
        
        # Define styles
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a202c'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2d3748'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        )
        
        subheading_style = ParagraphStyle(
            'CustomSubHeading',
            parent=styles['Heading3'],
            fontSize=12,
            textColor=colors.HexColor('#4a5568'),
            spaceAfter=10,
            fontName='Helvetica-Bold'
        )
        
        normal_style = styles['BodyText']
        
        # Title
        elements.append(Paragraph("Machine Learning Model Card", title_style))
        elements.append(Spacer(1, 12))
        
        # Metadata
        metadata_text = f"""
        <b>Dataset:</b> {dataset_name}<br/>
        <b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
        <b>Generated by:</b> Vizion ML Engine
        """
        elements.append(Paragraph(metadata_text, normal_style))
        elements.append(Spacer(1, 20))
        
        # Dataset Summary Section
        elements.append(Paragraph("Dataset Summary", heading_style))
        
        dataset_data = [
            ['Metric', 'Value'],
            ['Total Rows', f"{dataset_info.get('rows', 'N/A'):,}"],
            ['Total Columns', f"{dataset_info.get('columns', 'N/A'):,}"],
            ['Missing Values', f"{dataset_info.get('missing_values', 'N/A'):,}"],
            ['Numeric Features', str(dataset_info.get('numeric_features', 'N/A'))],
            ['Categorical Features', str(dataset_info.get('categorical_features', 'N/A'))]
        ]
        
        dataset_table = Table(dataset_data, colWidths=[3*inch, 3*inch])
        dataset_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4299e1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey])
        ]))
        
        elements.append(dataset_table)
        elements.append(Spacer(1, 20))
        
        # ML Configuration Section
        elements.append(Paragraph("ML Configuration", heading_style))
        
        task_type = ml_config.get('task_type', 'N/A').replace('_', ' ').title()
        target_col = ml_config.get('target_column', 'N/A')
        model_type = ml_config.get('model_type', 'Auto-selected')
        
        ml_config_data = [
            ['Configuration', 'Value'],
            ['Task Type', task_type],
            ['Target Column', target_col],
            ['Model Selected', model_type],
            ['Train-Test Split', '80-20']
        ]
        
        ml_config_table = Table(ml_config_data, colWidths=[3*inch, 3*inch])
        ml_config_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#48bb78')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey])
        ]))
        
        elements.append(ml_config_table)
        elements.append(Spacer(1, 20))
        
        # Model Performance Section
        elements.append(Paragraph("Model Performance", heading_style))
        
        performance_data = [['Metric', 'Value']]
        
        # Add relevant metrics based on what's available
        if metrics.get('accuracy') is not None:
            performance_data.append(['Accuracy', f"{metrics['accuracy']:.2%}"])
        if metrics.get('precision') is not None:
            performance_data.append(['Precision', f"{metrics['precision']:.2%}"])
        if metrics.get('recall') is not None:
            performance_data.append(['Recall', f"{metrics['recall']:.2%}"])
        if metrics.get('f1_score') is not None:
            performance_data.append(['F1-Score', f"{metrics['f1_score']:.2%}"])
        if metrics.get('r2_score') is not None:
            performance_data.append(['R² Score', f"{metrics['r2_score']:.4f}"])
        if metrics.get('mae') is not None:
            performance_data.append(['Mean Absolute Error', f"{metrics['mae']:.4f}"])
        if metrics.get('rmse') is not None:
            performance_data.append(['RMSE', f"{metrics['rmse']:.4f}"])
        
        if len(performance_data) > 1:
            performance_table = Table(performance_data, colWidths=[3*inch, 3*inch])
            performance_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ed8936')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey])
            ]))
            
            elements.append(performance_table)
        else:
            elements.append(Paragraph("No performance metrics available", normal_style))
        
        elements.append(Spacer(1, 20))
        
        # Feature Importance Section
        if feature_importance and len(feature_importance) > 0:
            elements.append(Paragraph("Top Features", heading_style))
            
            feature_data = [['Feature', 'Importance']]
            for feature, importance in feature_importance[:10]:
                feature_data.append([str(feature), f"{importance:.4f}"])
            
            feature_table = Table(feature_data, colWidths=[4*inch, 2*inch])
            feature_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#9f7aea')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey])
            ]))
            
            elements.append(feature_table)
            elements.append(Spacer(1, 20))
        
        # Charts Section
        if chart_paths and len(chart_paths) > 0:
            elements.append(PageBreak())
            elements.append(Paragraph("Visual Analysis", heading_style))
            elements.append(Spacer(1, 12))
            
            for chart_path in chart_paths:
                if os.path.exists(chart_path):
                    try:
                        img = Image(chart_path, width=6*inch, height=4*inch)
                        elements.append(img)
                        elements.append(Spacer(1, 12))
                    except Exception as e:
                        print(f"Could not add chart {chart_path}: {e}")
        
        # Recommendations Section
        elements.append(PageBreak())
        elements.append(Paragraph("Recommendations & Limitations", heading_style))
        
        recommendations = generate_recommendations(ml_config, metrics, dataset_info)
        
        for rec in recommendations:
            elements.append(Paragraph(f"• {rec}", normal_style))
            elements.append(Spacer(1, 6))
        
        elements.append(Spacer(1, 20))
        
        # Limitations
        elements.append(Paragraph("Limitations", subheading_style))
        limitations = [
            "This model was trained on the provided dataset and may not generalize to different data distributions",
            "Performance metrics are based on a single train-test split and may vary",
            "Model has not been validated on production data",
            "Regular retraining is recommended as new data becomes available",
            "Consider conducting additional validation before deployment"
        ]
        
        for limitation in limitations:
            elements.append(Paragraph(f"• {limitation}", normal_style))
            elements.append(Spacer(1, 6))
        
        # Footer
        elements.append(Spacer(1, 30))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
        elements.append(Paragraph("Generated by Vizion ML Engine | Automated Machine Learning Platform", footer_style))
        
        # Build PDF
        doc.build(elements)
        
        return True
    
    except Exception as e:
        print(f"Error generating PDF model card: {e}")
        return False


def generate_recommendations(ml_config: Dict, metrics: Dict, dataset_info: Dict) -> List[str]:
    """Generate intelligent recommendations based on model results."""
    
    recommendations = []
    
    # Check dataset size
    rows = dataset_info.get('rows', 0)
    if rows < 100:
        recommendations.append("Dataset is small (< 100 rows). Consider collecting more data for better model performance")
    elif rows < 1000:
        recommendations.append("Dataset size is moderate. More data could improve model reliability")
    
    # Check missing values
    missing = dataset_info.get('missing_values', 0)
    if missing > 0:
        recommendations.append(f"Dataset has {missing} missing values. Ensure appropriate imputation strategy is used")
    
    # Check model performance
    task_type = ml_config.get('task_type', '')
    
    if 'classification' in task_type:
        accuracy = metrics.get('accuracy', 0)
        if accuracy and accuracy < 0.7:
            recommendations.append("Model accuracy is below 70%. Consider feature engineering or trying different models")
        elif accuracy and accuracy > 0.9:
            recommendations.append("Very high accuracy detected. Verify there's no data leakage or overfitting")
        
        f1 = metrics.get('f1_score', 0)
        if f1 and f1 < 0.6:
            recommendations.append("Low F1-score suggests imbalanced classes. Consider using SMOTE or class weights")
    
    elif 'regression' in task_type:
        r2 = metrics.get('r2_score', 0)
        if r2 and r2 < 0.5:
            recommendations.append("Low R² score. Consider adding more relevant features or polynomial features")
        elif r2 and r2 > 0.95:
            recommendations.append("Very high R2 score. Verify model isn't overfitting")
    
    # General recommendations
    recommendations.append("Perform cross-validation to get more robust performance estimates")
    recommendations.append("Monitor model performance on new data regularly")
    recommendations.append("Consider hyperparameter tuning for improved results")
    recommendations.append("Document any data preprocessing steps for reproducibility")
    
    return recommendations


def generate_html_report(
    output_path: str,
    dataset_name: str,
    dataset_info: Dict,
    ml_config: Dict,
    metrics: Dict,
    execution_summary: str
) -> bool:
    """
    Generate a simple HTML report as an alternative to PDF.
    
    Returns:
        True if successful, False otherwise
    """
    try:
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ML Model Report - {dataset_name}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background: #f7fafc;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            text-align: center;
        }}
        .header h1 {{
            margin: 0;
            font-size: 2em;
        }}
        .section {{
            background: white;
            padding: 25px;
            margin-bottom: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .section h2 {{
            color: #2d3748;
            border-bottom: 3px solid #4299e1;
            padding-bottom: 10px;
            margin-top: 0;
        }}
        .metric {{
            display: inline-block;
            background: #edf2f7;
            padding: 15px 25px;
            margin: 10px;
            border-radius: 8px;
            text-align: center;
        }}
        .metric-label {{
            font-size: 0.9em;
            color: #718096;
            margin-bottom: 5px;
        }}
        .metric-value {{
            font-size: 1.5em;
            font-weight: bold;
            color: #2d3748;
        }}
        .recommendation {{
            background: #fef5e7;
            border-left: 4px solid #f39c12;
            padding: 15px;
            margin: 10px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
        }}
        th {{
            background: #4299e1;
            color: white;
        }}
        tr:hover {{
            background: #f7fafc;
        }}
        .footer {{
            text-align: center;
            color: #a0aec0;
            margin-top: 40px;
            padding: 20px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Machine Learning Model Report</h1>
        <p>Dataset: {dataset_name}</p>
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
    
    <div class="section">
        <h2>📊 Dataset Summary</h2>
        <div class="metric">
            <div class="metric-label">Total Rows</div>
            <div class="metric-value">{dataset_info.get('rows', 'N/A'):,}</div>
        </div>
        <div class="metric">
            <div class="metric-label">Total Columns</div>
            <div class="metric-value">{dataset_info.get('columns', 'N/A')}</div>
        </div>
        <div class="metric">
            <div class="metric-label">Missing Values</div>
            <div class="metric-value">{dataset_info.get('missing_values', 'N/A')}</div>
        </div>
    </div>
    
    <div class="section">
        <h2>⚙️ ML Configuration</h2>
        <table>
            <tr>
                <th>Configuration</th>
                <th>Value</th>
            </tr>
            <tr>
                <td>Task Type</td>
                <td>{ml_config.get('task_type', 'N/A').replace('_', ' ').title()}</td>
            </tr>
            <tr>
                <td>Target Column</td>
                <td>{ml_config.get('target_column', 'N/A')}</td>
            </tr>
            <tr>
                <td>Model Type</td>
                <td>{ml_config.get('model_type', 'Auto-selected')}</td>
            </tr>
        </table>
    </div>
    
    <div class="section">
        <h2>📈 Model Performance</h2>
        {execution_summary}
    </div>
    
    <div class="section">
        <h2>💡 Recommendations</h2>
        {''.join([f'<div class="recommendation">{rec}</div>' for rec in generate_recommendations(ml_config, metrics, dataset_info)])}
    </div>
    
    <div class="footer">
        <p>Generated by Vizion ML Engine | Automated Machine Learning Platform</p>
    </div>
</body>
</html>
"""
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return True
    
    except Exception as e:
        print(f"Error generating HTML report: {e}")
        return False
